version: '3'
services:
  db:
    container_name: local_db
    build: ./db/
    image: local_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
  app:
    container_name: local_app
    build: ./app/
    image: local_app
    ports:
      - 80:8000
    links:
      - db
    volumes:
      - ../laravel:/var/www/html/laravel
    stdin_open: true
    tty: true
    depends_on:
      - db
